### ISSUE TITLE
Doesn't show theme name in lxappearance 

### ISSUE THREAD

**Issue by mngshm** [phocus/gtk#11]
I installed phocus and configured it according to my preference but when I wanted to change the theme from lxappearance my theme option wasn't there in the list. I use bspwm. In xfce I was able to change the themes so far.

**Comment by phisch** [comment]
Lxappearance expects themes to come with a GTK2 and GTK3 theme. Phocus is GTK3 only, which is why it does not show up in lxappearance. Phocus won't add GTK2 support.
