### ISSUE TITLE
Radio and Check icons spacing issue, lists selected item highlight

### ISSUE THREAD

**Issue by pansy27** [phocus/gtk#14]
Hello.

I was messing with check and radio icons and found about their spacing issues in nemo's right click menu and gtk-inspector menu. The icons are too close to text. Here are some screenshots to explain what i mean: 
<br>
<h2> In Nemo right click menu :

![05_55_56](https://user-images.githubusercontent.com/88635622/175436724-43271daa-292c-43f3-95bc-cec74fd560cc.png)

<h2> In GTK-Inspector right click menu on selected text:

![05_55_20](https://user-images.githubusercontent.com/88635622/175437123-5917229d-6349-40de-9e03-02e9d7bae4c6.png)

<h2> In GTK-Inspector popover widget:

![05_56_21](https://user-images.githubusercontent.com/88635622/175437258-9d9aad7d-fa8b-4c87-95fa-588678c5db18.png)

<h2> Selected list item doesn't have any highlighting: 

![05_42_10](https://user-images.githubusercontent.com/88635622/175437378-4f31d260-7ab9-4d68-961d-41f8c327e35d.png)
making it hard to tell apart from non selected ones.

<h2> flowbox child doesn't have any highlight for currently selected item: 

![06_23_34](https://user-images.githubusercontent.com/88635622/175438694-6a5dc0c4-36b2-4001-8ebb-bdf673472761.png)

<h2> I tried fixing these issues on my fork and this is what i achieved:

![06_19_29](https://user-images.githubusercontent.com/88635622/175438328-d4a29802-010b-4ab1-ab8c-2b40238fdf84.png)

![06_18_47](https://user-images.githubusercontent.com/88635622/175438337-4ec93d7d-1e7f-4bfe-a6d6-41cc9b1964ec.png)

![06_19_13](https://user-images.githubusercontent.com/88635622/175438349-3428211f-ddbf-4b57-99bf-7764b9855e13.png)

![06_16_43](https://user-images.githubusercontent.com/88635622/175438359-1a4082ba-a415-4bf3-a34f-a7d1de33a511.png)

![06_17_34](https://user-images.githubusercontent.com/88635622/175438366-8da3d6e6-64e1-480f-88cb-710cab058a8e.png)
</h2>
^ the shadow effect looks quite ugly but works for now.
<hr>
This is on commit 945ad39

I can submit a pr if needed regarding these fixes.
on a side note, any plans on porting phocus to gtk4 ? phocus is like the perfect template to base your own theme on so was wondering if you had any plans on porting it.

Thanks for this awesome project :)

**Comment by phisch** [comment]
Thanks for the detailed issue. But to be honest, I'm not really motivated to continue detail work on Phocus GTK due to apps moving to GTK4 with libadwaita. I added a comment about the current GTK theming situation to the [README.md#about-gtk4](https://github.com/phocus/gtk#about-gtk4), you'll also find a workaround to get a somewhat acceptable phocus experience in GTK4 apps using libadwaita.

**Comment by pansy27** [comment]
Understandable. Thanks for the workaround.
