### ISSUE TITLE
border/border-less variant

### ISSUE THREAD

**Issue by phisch** [phocus/gtk#2]
Currently, the theme is designed for tiled window managers, which makes window-resizing impossible in traditional window managers.

In traditional window managers, GTK applications should have a margin on the `window decoration` node so they can be resized at the edges. In tiling window managers on the other hand, a margin on `window decoration` renders as the theme background (which is basically a large ugly border). Resizing isn't done by dragging the border of the window in tiling window managers.

This means we probably need a way to generate a default variant of the theme, containing drag areas, and a border-less variant without drag areas.

**Comment by 6gk** [comment]
ignore this, testing.
