### ISSUE TITLE
not building

### ISSUE THREAD

**Issue by Jimmysit0** [phocus/gtk#7]
▲ ~ git clone https://github.com/phocus/gtk.git phocus-gtk

Cloning into 'phocus-gtk'...
remote: Enumerating objects: 82, done.
remote: Counting objects: 100% (82/82), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 683 (delta 36), reused 66 (delta 34), pack-reused 601
Receiving objects: 100% (683/683), 111.26 KiB | 555.00 KiB/s, done.
Resolving deltas: 100% (353/353), done.
 ▲ ~ cd phocus-gtk
 ▲ ~/phocus-gtk cd                                                                                                                                           
 ▲ ~ cd phocus-gtk
 ▲ ~/phocus-gtk make                                                                                                                                         
npm install && npm run build

> node-sass@4.14.1 install /home/jimmy/phocus-gtk/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-88_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/linux-x64-88_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.14.1 postinstall /home/jimmy/phocus-gtk/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /home/jimmy/phocus-gtk/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/home/jimmy/phocus-gtk/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@15.5.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/jimmy/phocus-gtk/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/jimmy/phocus-gtk/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/jimmy/phocus-gtk/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/jimmy/phocus-gtk/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/jimmy/phocus-gtk/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/jimmy/phocus-gtk/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/jimmy/phocus-gtk/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/jimmy/phocus-gtk/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/jimmy/phocus-gtk/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/jimmy/phocus-gtk/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/jimmy/phocus-gtk/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/jimmy/phocus-gtk/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:199:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:333:12)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at maybeClose (node:internal/child_process:1063:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
gyp ERR! System Linux 5.10.6-arch1-1
gyp ERR! command "/usr/bin/node" "/home/jimmy/phocus-gtk/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/jimmy/phocus-gtk/node_modules/node-sass
gyp ERR! node -v v15.5.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.14.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jimmy/.npm/_logs/2021-01-13T23_35_19_122Z-debug.log
make: *** [Makefile:6: all] Error 1

**Comment by phisch** [comment]
Sorry for the wait. Switched from node-sass (which uses a wrapper around libsass which is unmaintained) to sass (which is compiled from dart-sass, the main sass implementation). Build should not break like this again.
