### ISSUE TITLE
Selected items are black in nemo

### ISSUE THREAD

**Issue by snakedye** [phocus/gtk#8]
selected:
![image](https://user-images.githubusercontent.com/49378990/106303169-cf886080-6227-11eb-9f48-e514eaaaeda3.png)
unselected:
![image](https://user-images.githubusercontent.com/49378990/106303248-eb8c0200-6227-11eb-8e8a-62e5541b0d29.png)

This affect icons as well as the text on the sidebar.

**Comment by phisch** [comment]
@snakedye So the sidebar is a normal GTK3 list widget, and the icons just take the same color as the text. I found that the `elementary` GTK theme does some stuff to color those icons separately (which i like), but i haven't looked it up in their code yet.

The main view on the other hand is a different story. It is a custom widget and i have no clue how it is styled. So if you have any information on this, i would appreciate it.

Also the styles for this will most likely be added as application specific styles, so they don't affect any other apps.

**Comment by snakedye** [comment]
Thanks, I will look into this and hopefully come back with a PR.

**Comment by phisch** [comment]
No need for a pr, some information would be enough.

**Comment by snakedye** [comment]
https://github.com/horst3180/arc-theme/blob/8290cb813f157a22e64ae58ac3dfb5983b0416e6/common/gtk-3.0/3.16/sass/_transparent_widgets.scss

**Comment by snakedye** [comment]
```css
  &:selected {
    background: $accent-7;
    color: $background-2;
  }
```
Changing this in /scss/components/_treeview.css yields this result.
![image](https://user-images.githubusercontent.com/49378990/112515327-8dcdef00-8d6c-11eb-90c4-16d64b61ede9.png)

**Comment by obliviousofcraps** [comment]
Something similar with selection in address bar in thunar, vivaldi, firefox, etc. can't distinguish between selected and not selected texts in the address bar . 
These ones have selected texts: 
![snap_21_05_10_16_43](https://user-images.githubusercontent.com/61628558/117650248-336bdf00-b1b0-11eb-8bd0-61a62b126008.png)
![snap_21_05_10_16_48](https://user-images.githubusercontent.com/61628558/117650255-349d0c00-b1b0-11eb-90be-334a882d7ff7.png)

and these are not selected. 

![snap_21_05_10_16_42](https://user-images.githubusercontent.com/61628558/117650340-4e3e5380-b1b0-11eb-8f29-fe9d6bd1a05a.png)
![snap_21_05_10_16_50](https://user-images.githubusercontent.com/61628558/117650344-4f6f8080-b1b0-11eb-8e19-22ce06487d02.png)

**Comment by phisch** [comment]
@obliviousofcraps it looks like you are running an old version of phocus, or you restyled it in a way in which this is caused. Current phocus has bright purple selections everywhere:

![firefox](https://user-images.githubusercontent.com/1282767/117651408-335ce680-b192-11eb-9772-259d63959fbc.png)
![thunar](https://user-images.githubusercontent.com/1282767/117651414-348e1380-b192-11eb-886e-6a5e5101bb6d.png)

There has been a lot of changes lately, so maybe you just didn't update in a while.

Edit: and the issue with the selected files in the file-view will be resolved in the near future.

**Comment by obliviousofcraps** [comment]
Okay, i'mma try and will let you know how it goes. 

Also which property do I need to play with to change the colors for that?

**Comment by phisch** [comment]
@obliviousofcraps currently it is the `$primary-accent` in https://github.com/phocus/gtk/blob/master/scss/gtk-3.0/_colors.scss#L16.
GTK3 phocus does not have a stable release yet (https://github.com/phocus/gtk/releases), which means this can change at any second, since i develop against the master branch, and i am still planning to restructure the options and colors to make it easier customizable, especially when there are dark and light variations and gtk3 plus gtk4 versions. (GTK2 will never be supported btw)

**Comment by phisch** [comment]
@snakedye i added some exceptions for nemo in the latest commits, it should look fine now:
![image](https://user-images.githubusercontent.com/1282767/162584246-a0f82e16-3f82-4d5f-ba3e-84cf4c11d971.png)

**Comment by phisch** [comment]
The latest nautilus update is also themed properly. Just a shame that the new adwaita folder icons look so horrible:
![image](https://user-images.githubusercontent.com/1282767/162584368-4fb9d16a-4a8d-4d16-b215-b9514d583bec.png)

**Comment by snakedye** [comment]
Eagerly waiting for philes and it's beautiful icons.

**Comment by phisch** [comment]
@snakedye not gonna happen, but here is a screenshot of what pholders could have become if I would not have much more interesting things to work on:
![image](https://user-images.githubusercontent.com/1282767/162587810-c741cf78-c1e4-404e-b180-5ce569847641.png)

**Comment by snakedye** [comment]
Really nice, it has the flat style of Papirus which I'm currently using. I found it weird Adwaita doesn't have flat icons when the whole theme is now flat.
